spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/prigione_records
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s

server:
  port: 8080
  # servlet:
  #   context-path: /api

# Configurazione JWT
jwt:
  secret: ${JWT_SECRET:chiaveSegretaMoltoPiuLungaPerGarantireMaggioreSicurezzaNellaGenerazioneDeiToken}
  expiration: 86400000 # 24 ore in millisecondi
  refresh-expiration: 604800000 # 7 giorni in millisecondi

# Configurazione SpringDoc OpenAPI (Swagger)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: false
  packages-to-scan: com.prigione.controller

# Configurazione logging
logging:
  level:
    root: INFO
    com.prigione: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.security: INFO

# Configurazione rate limiting
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: true